<style>
td {
	border: thin solid gray;
}
</style>
<section>
    <h1>Guestbook</h1>

    <section>
        <h1>Create a new entry</h1>

        <?php
        $form = $this->entryForm;
        $form->setAttribute('action', $this->url('guestbook'));
        $form->setAttribute('method', 'post');
        $form->prepare();
        ?>

        <?php echo $this->form()->openTag($form) ?>
        <dl>
            <dt><?php 
            $name = $form->get('name');
            echo $this->formLabel($name); ?></dt>
            <dd><?php echo $this->formText($name) . $this->formElementErrors($name); ?></dd>

            <dt><?php echo $this->formLabel($form->get('email')); ?></dt>
            <dd><?php echo $this->formEmail($form->get('email')) . $this->formElementErrors($form->get('email')); ?></dd>

            <dt><?php echo $this->formLabel($form->get('website')); ?></dt>
            <dd><?php echo $this->formUrl($form->get('website')) . $this->formElementErrors($form->get('website')); ?></dd>

            <dt><?php echo $this->formLabel($form->get('message')); ?></dt>
            <dd><?php echo $this->formTextarea($form->get('message')) . $this->formElementErrors($form->get('message')); ?></dd>

            <dd><?php echo $this->formSubmit($form->get('submit')); ?></dd>
        </dl>
        <?php echo $this->form()->closeTag() ?>
    </section>

</section>